import Augmentor

p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hack18/copied_images/h18_empty")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.sample(5000)
p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hack18/copied_images/h18_poo")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.sample(5000)
p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hack18/copied_images/h18_pee")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.sample(5000)
p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hack18/copied_images/h18_poopee")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.sample(5000)
p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hack18/copied_images/h18_peepaper")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.sample(5000)
p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hack18/copied_images/h18_poopaper")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.sample(5000)
exit()


p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hack18/copied_images")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
#p.resize(probability=0.3, width=120, height=120)
p.sample(5000)
exit()

p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hackathon18/dataset_raw/paper")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.resize(probability=0.3, width=120, height=120)
p.sample(10000)

p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hackathon18/dataset_raw/pee")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.zoom(probability=0.5, min_factor=1.1, max_factor=1.5)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.crop_random(probability=0.3, percentage_area=0.5)
p.resize(probability=0.3, width=120, height=120)
p.sample(10000)

p = Augmentor.Pipeline("/media/Storage/CFolder/GitHub/Hackathon18/dataset_raw/poo")
p.rotate(probability=1, max_left_rotation=25, max_right_rotation=25)
p.rotate90(probability=0.3)
p.rotate180(probability=0.3)
p.rotate270(probability=0.3)
p.zoom(probability=0.5, min_factor=1.1, max_factor=1.5)
p.flip_left_right(probability=0.5)
p.flip_top_bottom(probability=0.5)
p.crop_random(probability=0.3, percentage_area=0.5)
p.resize(probability=0.3, width=120, height=120)
p.sample(10000)